/**
 * Canonical enumerations from /contracts/enums
 */

/**
 * Event Types
 */
export enum EventType {
  SIGNAL_CREATED = 'SIGNAL_CREATED',
  SIGNAL_UPDATED = 'SIGNAL_UPDATED',
  SIGNAL_CANCELLED = 'SIGNAL_CANCELLED',
  DIRECTIVE_CREATED = 'DIRECTIVE_CREATED',
  DIRECTIVE_PROCESSED = 'DIRECTIVE_PROCESSED',
  DIRECTIVE_COMPLETED = 'DIRECTIVE_COMPLETED',
  DIRECTIVE_FAILED = 'DIRECTIVE_FAILED',
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  ORDER_OPENED = 'ORDER_OPENED',
  ORDER_MODIFIED = 'ORDER_MODIFIED',
  ORDER_CLOSED = 'ORDER_CLOSED',
}

/**
 * Error Classes
 */
export enum ErrorClass {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
  BROKER_ERROR = 'BROKER_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

/**
 * Signal Direction
 */
export enum SignalDirection {
  BUY = 'BUY',
  SELL = 'SELL',
}

/**
 * Signal Status
 */
export enum SignalStatus {
  PENDING = 'pending',
  ACTIVE = 'active',
  FILLED = 'filled',
  CANCELLED = 'cancelled',
}
